// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/miremovependrive.png
var resourceAppIconPngData []byte
var resourceAppIconPng = &fyne.StaticResource{
	StaticName:    "icon/miremovependrive.png",
	StaticContent: resourceAppIconPngData,
}
